---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flux-system.yaml
  - flux-sync.yaml

patchesJson6902:
  - target:
      version: v1
      kind: ServiceAccount
      name: kustomize-controller
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          eks.amazonaws.com/role-arn: <KMS_ROLE_ARN>